name: 'cells'

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10.*
  - pip
  - cudatoolkit=11.2.2
  - cudnn=8.1.0.77
  - pip:
      - stardist==0.8.5
      - tensorflow==2.10.1
      - numpy==1.24.4
      - -e .